"""
报告生成副作用。

将管线推荐结果生成 Markdown 报告文件，落盘到本地和数据库。
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List, Optional

from config import get_config
from logger import get_monitor_logger
from pipeline.base import BaseSideEffect
from pipeline.models import ContentItem, ContentType, PipelineContext
from storage import Storage, get_storage


class ReportEffect(BaseSideEffect):
    """基于管线推荐结果生成 Markdown 报告。"""

    effect_name = "report_generate"

    def __init__(self, storage: Optional[Storage] = None, output_dir: Optional[str] = None):
        self._storage = storage
        self.output_dir = output_dir or get_config().reporting.output_dir
        self.logger = get_monitor_logger()

    async def _get_storage(self) -> Storage:
        if self._storage is None:
            self._storage = await get_storage()
        return self._storage

    async def execute(
        self, items: List[ContentItem], context: PipelineContext
    ) -> None:
        """生成推荐报告。"""
        if not items:
            self.logger.debug("无推荐结果，跳过报告生成")
            return

        now = datetime.now()
        title = f"Pipeline Report - {now.strftime('%Y-%m-%d %H:%M')}"
        content = self._render_report(items, context, title)

        # 写入文件
        file_path = self._write_file(title, content)
        self.logger.info(f"管线报告已生成: {file_path}")

        # 落库
        storage = await self._get_storage()
        await storage.save_report(
            report_type="pipeline",
            title=title,
            content=content,
            lookback_hours=0,
        )

    def _render_report(
        self, items: List[ContentItem], context: PipelineContext, title: str
    ) -> str:
        """渲染 Markdown 报告。"""
        lines = [
            f"# {title}",
            "",
            f"- Query: {context.query or 'N/A'}",
            f"- Total sourced: {sum(context.source_counts.values())}",
            f"- After filtering: {len([i for i in items])}",
            f"- Selected: {len(items)}",
            f"- Generated at: {datetime.now().isoformat()}",
            "",
        ]

        # 按来源统计
        lines.append("## Source Distribution")
        lines.append("")
        for source, count in sorted(context.source_counts.items()):
            lines.append(f"- {source}: {count}")
        lines.append("")

        # Top 推荐
        lines.append("## Top Recommendations")
        lines.append("")

        for i, item in enumerate(items[:20], 1):
            emoji = self._type_emoji(item.content_type)
            symbols_str = ", ".join(item.symbols[:3]) if item.symbols else "N/A"
            lines.append(f"### {i}. {emoji} {item.title[:80]}")
            lines.append("")
            lines.append(f"- **Source**: {item.source} | **Type**: {item.content_type.value}")
            lines.append(f"- **Symbols**: {symbols_str}")
            lines.append(
                f"- **Scores**: Hotness={item.score_hotness:.0f} "
                f"Credibility={item.score_credibility:.0f} "
                f"Impact={item.score_impact:.0f} "
                f"Relevance={item.score_relevance:.0f} "
                f"**Final={item.score_final:.0f}**"
            )
            if item.risk_tags:
                lines.append(f"- **Risk Tags**: {', '.join(item.risk_tags)}")
            if item.sentiment:
                lines.append(f"- **Sentiment**: {item.sentiment}")
            if item.body:
                body_preview = item.body[:150].replace("\n", " ")
                lines.append(f"- **Preview**: {body_preview}")
            if item.url:
                lines.append(f"- **URL**: {item.url}")
            lines.append("")

        # Filter 统计
        if context.filter_stats:
            lines.append("## Filter Statistics")
            lines.append("")
            for filter_name, count in sorted(context.filter_stats.items()):
                lines.append(f"- {filter_name}: filtered {count} items")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Crypto Monitor Pipeline*")

        return "\n".join(lines)

    def _write_file(self, title: str, content: str) -> Path:
        """写入报告文件。"""
        output_dir = Path(self.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        slug = datetime.now().strftime("%Y%m%d-%H%M%S")
        file_path = output_dir / f"pipeline-report-{slug}.md"
        file_path.write_text(content, encoding="utf-8")
        return file_path

    @staticmethod
    def _type_emoji(content_type: ContentType) -> str:
        mapping = {
            ContentType.NEWS: "📰",
            ContentType.KOL_OPINION: "🗣",
            ContentType.ONCHAIN_ALERT: "⛓",
            ContentType.PRICE_MOVEMENT: "📈",
            ContentType.RISK_WARNING: "🚨",
            ContentType.YOUTUBE_VIDEO: "🎬",
            ContentType.REDDIT_POST: "💬",
            ContentType.TWITTER_POST: "🐦",
        }
        return mapping.get(content_type, "📌")
